### ISSUE TITLE
Integrate Komiser Docusaurus with Algolia DocSearch

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/docs.komiser.io#49]
DocSearch works by crawling the content of your website every 24 hours and putting all the content in an Algolia index. This content is then queried directly from your front-end using the Algolia API. Note that your website needs to be publicly available for this to work (ie. not behind a firewall). This service is free.

We would like to add Algolia DocSearch functionalities to our docs. We have already applied got the required licence (and API key) 
Instructions [here](https://v1.docusaurus.io/docs/en/search). Reach out to @jakepage91 to get the `apiKey` needed for this integreation.

**Comment by gokuljs** [comment]
@jakepage91 can you pass me the apiKey

**Comment by jakepage91** [comment]
Hey there @gokuljs I will send it to you shortly (we recently changed our email extension and I will have to request the API key again since I can't find it in my inbox.) Will keep you posted thanks.

**Comment by jakepage91** [comment]
Found it, here is the public API key @gokuljs 
```
9983878ae17ae51850aa1eefd20aef16
```

**Comment by gokuljs** [comment]
Great, Thanks will try to integrate once I am free or over the weekend.

**Comment by gokuljs** [comment]
@jakepage91, can you please send me the indexName from your Alogila account 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/51263906/235324543-cc00adbb-71f9-48c2-b04c-d131e3a5d2cd.png">
